### PR TITLE
[HOLD] Merge with Poseidon

### PR DESCRIPTION
**Pull request by MrMaksimize**
Still to do:

- [x] Additional executors and prod prep
- [x] Move secrets to json, abstract secret_manager
- [x] Make commander into fire script; Merge with secret_manager
- [x] Wrap commander around docker cleanup
- [x] Check logging issue
- [x] Test run the dags
- [x] Figure out start date
- [x] Look through dags for backfill opportunities
- [x] Migrate s3 operators to boto3
- [x] Review prod login system
- [x] Clean out general.py
- [x] Clean out geospatial.py
- [x] Temp file maintenance?
- [x] Implement CircleCI Basics
- [x] Write some docs
- [x] Bring in original AF docs
- [x] Oracle Client Library problem
- [x] Incorrect padding problem for MS SQL databases
- [x] Missing libraries: mapshaper and rtree
- [x] S3 conn id argument problem while uploading

### CODE REVIEW

**Comment by andrell81** [comment]
Ran into issue uploading

screen shot 2019-02-22 at 2 08 23 pm

**Comment by andrell81** [comment]
Also got this error when trying to send an email with poseidon

screen shot 2019-02-22 at 3 54 47 pm

**Comment by andrell81** [comment]
Ut oh, Oracle error

screen shot 2019-02-22 at 3 59 26 pm

**Comment by andrell81** [comment]
Having some kind of issue getting into a ms sql database.

This might help: https://github.com/puckel/docker-airflow/issues/290

screen shot 2019-02-22 at 4 25 38 pm

**Comment by andrell81** [comment]
Tried a spatial join, and apparently we're missing a module called rtree.

screen shot 2019-02-27 at 2 40 59 pm

**Comment by andrell81** [comment]
Ugghhh, we need mapshaper

screen shot 2019-02-28 at 10 54 55 am

**Comment by andrell81** [comment]
@MrMaksimize I tested as many tasks from as many dags as possible. 

Major problems are:
- Oracle Client Library problem
- Incorrect padding problem for MS SQL databases
- Missing libraries: mapshaper and rtree
- S3 conn id argument problem while uploading

So, we have only 6 dags that have been fully tested (minus upload, which is broken) and are working: budget, inventory, pd_col, read, traffic_counts, and public art.

5 dags couldn't be tested because of the Oracle error: ttcs, indicator_bacteria, dsd_permits, cip, and tsw_integration

10 dags couldn't be tested because of MS SQL error: docmntm_others, documentum_24_docs, obdocs, sire_docs, streets_imcat, streets_sdif, special_events, fd_incidents, fd_problem_nature, and sidewalk

29 GIS files can't be tested until mapshaper is added

get_it_done is waiting on rtree add

**Comment by MrMaksimize** [comment]
@andrell81 excellent

Tweaking some of this stuff now

**Comment by andrell81** [comment]
Sadly, another error with MS SQL @MrMaksimize 

screen shot 2019-03-06 at 4 13 10 pm

**Comment by andrell81** [comment]
Retested, and the only error is the MS SQL error referenced earlier. All of the Oracle dags and GIS dags are working.

**Comment by andrell81** [comment]
Sorreee, but I forgot to test md updates until now. Found this error

Screen Shot 2019-03-14 at 4 27 01 PM

**Pull request merged**
